version: "2"
services:
    mysql:
        image: mysql:5.7.8
        restart: always
        ports:
        - "3306:3306"
        environment:
        - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        volumes:
        - /data/mysql:/var/lib/mysql:rw
    redis:
        image: redis:3.0.7
        restart: always
        ports:
        - "6379:6379"
        volumes:
        - /data/redis:/data:rw
