database:
  name: testnote
  host: 127.0.0.1
  port: 3306
  username: root
  password:
  logging: false

cache:
  host: 127.0.0.1
  port: 6379
  db: 0

jwt:
  secret: 3vzNBnSdF8cP6kpP6ncf
  algorithm: RS256
  exp: 5184000000

sentry:
  uri: 

env: test
port: 0
